ALTER DATABASE ProjectManage
SET FILESTREAM ( NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = N'本级文件' )

ALTER DATABASE ProjectManage 
SET FILESTREAM ( NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = N'程序文件' )

ALTER DATABASE ProjectManage 
SET FILESTREAM ( NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = N'公司文件' )

ALTER DATABASE ProjectManage 
SET FILESTREAM ( NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = N'临时文件' )

ALTER DATABASE ProjectManage 
SET FILESTREAM ( NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = N'设计文件' )

ALTER DATABASE ProjectManage 
SET FILESTREAM ( NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = N'施工图纸' )

ALTER DATABASE ProjectManage 
SET FILESTREAM ( NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = N'施工文件' )